//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nostrum.railwaycar.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("nostrum.railwaycar.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;RailwayCarTypes&gt;
        ///  &lt;RailwayCarData d1=&quot;2&quot; CarType=&quot;Крытый&quot; MainCharacteristic=&quot;4-осный, объем кузова менее 120 куб.м.&quot; AdditionalCharacteristic=&quot;характеристики не содержит&quot; TareWeight=&quot;22.7&quot; Length=&quot;14730&quot; TypeNumber=&quot;200&quot; IsPrivate=&quot;false&quot; d2_min=&quot;0&quot; d2_max=&quot;0&quot; d3_min=&quot;0&quot; d3_max=&quot;9&quot; d4_min=&quot;0&quot; d4_max=&quot;9&quot; d5_min=&quot;0&quot; d5_max=&quot;9&quot; d6_min=&quot;0&quot; d6_max=&quot;9&quot; d7_min=&quot;0&quot; d7_max=&quot;8&quot; HasBrakePad=&quot;false&quot; /&gt;
        ///  &lt;RailwayCarData d1=&quot;2&quot; CarType=&quot;Крытый&quot; MainCharacteristic=&quot;4-осный, об [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string car_types {
            get {
                return ResourceManager.GetString("car_types", resourceCulture);
            }
        }
    }
}
